notifications:
    email: false
dist: trusty
language: python
python: 2.7
services:
    - postgresql
addons:
    postgresql: "9.5"
cache: pip
before_install:
    - sudo apt-get install locate
    - sudo updatedb
install:
    - pip install --upgrade pip
    - pip install -e git+https://github.com/aiidateam/aiida_core@300a8e234b2836aef9cd71175903583bbfd1ae8b#egg=aiida-core
    - pip install -e git+https://github.com/aiidateam/aiida-wannier90#egg=aiida-wannier90
      #- pip install -e git+https://github.com/greschd/aiida_pytest#egg=aiida_pytest
    - pip install -e .[regen_default_paws,graphs,dev]
    - pip install tox-travis coveralls
env:
    - TEST_TYPE="pre-commit"
    - TEST_TYPE="unittests" TOX_ENV=py27-aiida_11
    - TEST_TYPE="unittests" TOX_ENV=py27-aiida_stable
    - TEST_TYPE="unittests" TOX_ENV=py27-aiida_dev
script: travis_wait ./run_ci_tests.sh
after_success:
    - coverage combine
    - coveralls
