notifications:
    email: false
dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "9.6"
  apt:
    packages:
      - rabbitmq-server
cache: pip
before_install:
  - sudo .ci/enable_ssh_localhost.sh
  - sudo apt-get install locate
  - sudo updatedb
install:
  - pip install --upgrade pip
  - pip install -e git+https://github.com/aiidateam/aiida_core#egg=aiida-core
  - pip install -e git+https://github.com/aiidateam/aiida-wannier90#egg=aiida-wannier90
  - pip install -e .[graphs,dev]
  - pip install tox-travis
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then pip install coveralls; fi
script:
  - pre-commit run --all-files || ( git diff; git status; exit 1; )
  - tox
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then pytest --cov-report=term-missing --cov-append --cov=aiida_vasp; fi
after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then coveralls; fi
