notifications:
    email: false
dist: xenial
language: python
python:
  - 3.7
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "9.6"
  apt:
    packages:
      - rabbitmq-server
cache: pip
before_install:
  - sudo .ci/enable_ssh_localhost.sh
  - sudo apt-get install locate
  - sudo updatedb
install:
  - pip install --upgrade pip
  - pip install -e git+https://github.com/aiidateam/aiida_core#egg=aiida-core
  - pip install -e git+https://github.com/aiidateam/aiida-wannier90#egg=aiida-wannier90
  #- pip install -e git+https://github.com/greschd/aiida_pytest#egg=aiida_pytest
  - pip install -e .[regen_default_paws,graphs,dev]
  - pip install tox-travis coveralls
  - prospector --version
  - yapf --version
  - pylint --version
  - pre-commit --version
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="unittests" TOX_ENV=py37-aiida_dev
script: travis_wait .ci/run_ci_tests.sh
after_success:
  - coverage combine
  - coveralls
